### ISSUE TITLE
video is playing for 1 sec and stopping automatically in inline mode. (Android)

### ISSUE THREAD

**Issue by samuelchow1997** [davidohayon669/react-native-youtube#421] opened 2019-11-26 12:47 UTC
if video is playing on inline mode, it will play for 1s then stop automatically.

**Comment by nic-thomson** [comment] 2019-12-02 14:35
I too am seeing exactly the same thing ?

**Comment by gigagvenetadze** [comment] 2019-12-03 15:04
me too

**Comment by nic-thomson** [comment] 2019-12-03 15:09
it is actually the dreaded `overlay error`  it is discussed in detail here https://github.com/inProgress-team/react-native-youtube/issues/161

to see the error add this to your youtube control 
`onError={e => console.log('youtube error->',e)}`

**Comment by saravanakumargn** [comment] 2019-12-05 09:26
I got ```{"error": "UNAUTHORIZED_OVERLAY", "target": 6955}``` error and the below code s working for me.

```

const [iscontainerMounted, setIsContainerMounted] = useState(false);
const [containerWidth, setContainerWidth] = useState();

return (
<View
	style={{
	  flex: 1,
	}}
	onLayout={({
	  nativeEvent: {
		layout: { width },
	  },
	}) => {
	  if (!iscontainerMounted) setIsContainerMounted(true);
	  if (containerWidth !== width) setContainerWidth(width);
	}}
	>
	{iscontainerMounted && (
	  <YouTube
		apiKey={constants.YT_KEY}
		videoId={videoData.id.videoId}
		play
		style={{
		  alignSelf: 'stretch',
		  height: PixelRatio.roundToNearestPixel(containerWidth / (16 / 9)),
		}}
	  />
	)}
</View>
);
```

**Comment by yangga** [comment] 2019-12-07 01:50
Same here

**Comment by sidferreira** [comment] 2020-01-08 13:45
Having the same issue on iOS...

**Comment by harshalcent** [comment] 2020-01-20 07:10
Facing same issue on android only

**Comment by Tautorn** [comment] 2020-02-01 23:48
Same error here, state rendering:

 LOG  this.state {}
 LOG  this.state {"status": "stopped"}
 LOG  this.state {"status": "loading"}
 LOG  this.state {"isReady": true, "status": "loading"}

Component:

```
<YouTube
          autoplay
          apiKey="xxx"
          videoId="KVZ-P-ZI6W4"
          controls={0}
          onReady={e => this.setState({ isReady: true })}
          onChangeState={e => this.setState({ status: e.state })}
          onChangeQuality={e => this.setState({ quality: e.quality })}
          onError={e => this.setState({ error: e.error })}
          style={{ alignSelf: 'stretch', height: 300 }}
        />
```

**Comment by Tautorn** [comment] 2020-02-01 23:54
@samuelchow1997 I put `controls={1}` like parameter and it worked for me, code example:

```
<YouTube
          autoplay
          apiKey="xxx"
          videoId="KVZ-P-ZI6W4"
          controls={1}
          onReady={e => this.setState({ isReady: true })}
          onChangeState={e => this.setState({ status: e.state })}
          onChangeQuality={e => this.setState({ quality: e.quality })}
          onError={e => this.setState({ error: e.error })}
          style={{ alignSelf: 'stretch', height: 300 }}
        />
```

**Comment by cheebhodh** [comment] 2020-02-08 09:18
Same with me T_T

**Comment by sidferreira** [comment] 2020-02-10 11:55
When this happened to me, it was a native error issue.

**Comment by kishanbharda** [comment] 2020-02-22 08:24
Same issue happing with me. Video playing 1 or 2 second and then stops. If I play again it again stops after 1 or 2 seconds.

**Comment by OmarBasem** [comment] 2020-02-28 17:01
SAME ISSSUE

**Comment by davidohayon669** [comment] 2020-03-04 23:32
Duplicate of #161

**Closed by davidohayon669** 2020-03-04 23:32 UTC

**Comment by hienpham2102** [comment] 2020-06-04 03:29
same issue, anyone has the solution?

**Comment by babarbahadur** [comment] 2021-07-26 10:40
Same issue any solution?
